### ISSUE TITLE
Reproducing your paper

### ISSUE THREAD

**Issue by guilherme-pombo** [thwjoy/revae-demo#2] opened 2020-10-23 11:05 UTC
Hello, I've tried to reproduce the training algorithm using the details from your paper and I haven't been able to get close to the results you present on it. It would be very helpful if you could post the code for it or at least some pseudo-functioning code for it? Fashion-MNIST seems to work ok, but for CelebA it's not close at all.

**Comment by thwjoy** [comment] 2020-10-23 11:37
In what way do you mean it's not close at all?

The code will be released shortly, I'll let you know when it's uploaded!
Best Wishes,
Tom

Tom Joy
DPhil Candidate in Machine Learning

thomas.joy@eng.ox.ac.uk (https://link.getmailspring.com/link/2BA3C71F-0A59-4B1A-8BA0-852C36552C46@getmailspring.com/0?redirect=%E2%80%9Cmailto%3Athomas.joy%40eng.ox.ac.uk%E2%80%9D&recipient=cmVwbHkrQUZVUTNQTkNWUUVONkhLVktYQkhCTE41VDJOQkxFVkJOSEhDV1pTWDRFQHJlcGx5LmdpdGh1Yi5jb20%3D)
https://thwjoy.github.io (https://link.getmailspring.com/link/2BA3C71F-0A59-4B1A-8BA0-852C36552C46@getmailspring.com/1?redirect=https%3A%2F%2Fthwjoy.github.io&recipient=cmVwbHkrQUZVUTNQTkNWUUVONkhLVktYQkhCTE41VDJOQkxFVkJOSEhDV1pTWDRFQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by guilherme-pombo** [comment] 2020-10-27 11:23
I've got it a bit closer now, but basically the interventions I do on CelebA, don't produce images as coherent as the ones presented on your paper. Look forward to seeing the nuances of your training code

**Comment by adriaan-lambrechts** [comment] 2021-03-08 13:25
Hi Tom,

Do you have already an idea when you'll be able to share the training code for reproducability of your paper?

**Comment by thwjoy** [comment] 2021-03-08 13:36
Hi Adrian,

Yes it should be up next week sometime, the reason for the late upload is we were waiting for it to be accepted into ICLR, see new paper: https://openreview.net/forum?id=wQRlSUZ5V7B.

Best Wishes,
Tom

Tom Joy
DPhil Candidate in Machine Learning

thomas.joy@eng.ox.ac.uk (mailto:thomas.joy@eng.ox.ac.uk)
http://thwjoy@github.io

**Comment by thwjoy** [comment] 2021-03-26 08:46
Hi All,

Apologies for the long delay, the training code for our ICLR work is here: https://github.com/thwjoy/ccvae.

Enjoy!

**Closed as completed** 2024-06-19 10:06 UTC
